// <auto-generated />
using System;
using AgriManage.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgriManage.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251218125602_FixCascadePaths")]
    partial class FixCascadePaths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgriManage.DataAccess.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TamAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.AraziTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AraziTipleri");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.BakimKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BakimPlaniId")
                        .HasColumnType("int");

                    b.Property<decimal>("Maliyet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BakimPlaniId");

                    b.HasIndex("PersonelId");

                    b.ToTable("BakimKayitlari");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.BakimPlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BakimTipiId")
                        .HasColumnType("int");

                    b.Property<int>("EkipmanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlanlananTarih")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Tamamlandi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BakimTipiId");

                    b.HasIndex("EkipmanId");

                    b.ToTable("BakimPlanlari");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.BakimTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BakimTipleri");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Bolge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Bolgeler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Trakya Bölgesi"
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departmanlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ziraat Operasyonları"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Teknik Bakım"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Stok ve Lojistik"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Yönetim"
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Depo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LokasyonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LokasyonId");

                    b.ToTable("Depolar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ana Gübre Deposu",
                            LokasyonId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Zirai İlaç Deposu",
                            LokasyonId = 1
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Lojistik Merkezi",
                            LokasyonId = 2
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.EkimPlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BeklenenVerimKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EkimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GerceklesenVerimKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("HasatTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SezonId")
                        .HasColumnType("int");

                    b.Property<int>("TarlaId")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SezonId");

                    b.HasIndex("TarlaId");

                    b.HasIndex("UrunId");

                    b.ToTable("EkimPlanlari");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Ekipman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("EkipmanDurumuId")
                        .HasColumnType("int");

                    b.Property<int>("EkipmanKategorisiId")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SeriNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EkipmanDurumuId");

                    b.HasIndex("EkipmanKategorisiId");

                    b.ToTable("Ekipmanlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Büyük Kırmızı Traktör",
                            EkipmanDurumuId = 1,
                            EkipmanKategorisiId = 1,
                            Marka = "Case IH",
                            Model = "Puma 240",
                            SeriNo = "TR-001"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ekim Mibzeri",
                            EkipmanDurumuId = 1,
                            EkipmanKategorisiId = 2,
                            Marka = "Paksan",
                            Model = "24'lü",
                            SeriNo = "TR-002"
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.EkipmanDurumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EkipmanDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Aktif"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Bakımda"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Arızalı"
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.EkipmanKategorisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EkipmanKategorileri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Traktörler"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ekim Ekipmanları"
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.EkipmanLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EkipmanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EkipmanId");

                    b.ToTable("EkipmanLoglari");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GorevDurumuId")
                        .HasColumnType("int");

                    b.Property<int>("GorevTipiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlanlananBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TarlaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GorevDurumuId");

                    b.HasIndex("GorevTipiId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("TarlaId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.GorevDurumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("GorevDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Atandı"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Devam Ediyor"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Tamamlandı"
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.GorevLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.ToTable("GorevLoglari");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.GorevTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("GorevTipleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ekim"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Gübreleme"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "İlaçlama"
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Lokasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BolgeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BolgeId");

                    b.ToTable("Lokasyonlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Merkez Çiftlik (Lüleburgaz)",
                            Adres = "Lüleburgaz Yolu Üzeri",
                            BolgeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Tekirdağ Depo",
                            Adres = "Tekirdağ Liman",
                            BolgeId = 1
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.OperasyonelRapor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<string>("RaporOzeti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RaporTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.ToTable("OperasyonelRaporlar");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("IseBaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("PozisyonId")
                        .HasColumnType("int");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.HasIndex("PozisyonId");

                    b.ToTable("Personeller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IseBaslamaTarihi = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PozisyonId = 1,
                            SicilNo = "P-001"
                        },
                        new
                        {
                            Id = 2,
                            IseBaslamaTarihi = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PozisyonId = 2,
                            SicilNo = "P-002"
                        },
                        new
                        {
                            Id = 3,
                            IseBaslamaTarihi = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PozisyonId = 3,
                            SicilNo = "P-003"
                        },
                        new
                        {
                            Id = 4,
                            IseBaslamaTarihi = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PozisyonId = 4,
                            SicilNo = "P-004"
                        },
                        new
                        {
                            Id = 5,
                            IseBaslamaTarihi = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PozisyonId = 5,
                            SicilNo = "P-005"
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.PersonelVardiya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gun")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("VardiyaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("VardiyaId");

                    b.ToTable("PersonelVardiyalari");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Pozisyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.ToTable("Pozisyonlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Yönetici",
                            DepartmanId = 4
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ziraat Mühendisi",
                            DepartmanId = 1
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Traktör Operatörü",
                            DepartmanId = 1
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Bakım Teknisyeni",
                            DepartmanId = 2
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Depo Sorumlusu",
                            DepartmanId = 3
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.PozisyonYetki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PozisyonId")
                        .HasColumnType("int");

                    b.Property<int>("YetkiAlaniId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PozisyonId");

                    b.HasIndex("YetkiAlaniId");

                    b.ToTable("PozisyonYetkileri");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Sera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("AlanMetrekare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LokasyonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LokasyonId");

                    b.ToTable("Seralar");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Sezon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sezonlar");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.StokHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepoId")
                        .HasColumnType("int");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OperasyonelRaporId")
                        .HasColumnType("int");

                    b.Property<int>("StokItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TedarikciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepoId");

                    b.HasIndex("OperasyonelRaporId");

                    b.HasIndex("StokItemId");

                    b.HasIndex("TedarikciId");

                    b.ToTable("StokHareketleri");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.StokItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DepoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StokKategorisiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepoId");

                    b.HasIndex("StokKategorisiId");

                    b.ToTable("StokItemleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "DAP Gübresi",
                            Birim = "KG",
                            DepoId = 1,
                            Miktar = 500m,
                            StokKategorisiId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ad = "ÜRE Gübresi",
                            Birim = "KG",
                            DepoId = 1,
                            Miktar = 1000m,
                            StokKategorisiId = 1
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.StokKategorisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StokKategorileri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Gübreler"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Tohumlar"
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Tarla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("AlanDonum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LokasyonId")
                        .HasColumnType("int");

                    b.Property<string>("TapuAdaParsel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LokasyonId");

                    b.ToTable("Tarlalar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ana Tarla - A1",
                            AlanDonum = 150m,
                            LokasyonId = 1,
                            TapuAdaParsel = "101/1"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Dere Kenarı - B2",
                            AlanDonum = 85m,
                            LokasyonId = 1,
                            TapuAdaParsel = "102/3"
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.TarlaAraziTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AraziTipiId")
                        .HasColumnType("int");

                    b.Property<int>("TarlaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AraziTipiId");

                    b.HasIndex("TarlaId");

                    b.ToTable("TarlaAraziTipleri");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Tedarikci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("YetkiliKisi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tedarikciler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Anadolu Tarım A.Ş.",
                            Adres = "Lüleburgaz Sanayi Sitesi",
                            Telefon = "0532 123 45 67",
                            YetkiliKisi = "Ahmet Yılmaz"
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BeklenenRekolte")
                        .HasColumnType("float");

                    b.Property<DateTime>("EkimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HasatTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TarlaId")
                        .HasColumnType("int");

                    b.Property<int>("UrunKategorisiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TarlaId");

                    b.HasIndex("UrunKategorisiId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Buğday (Ceyhan-99)",
                            BeklenenRekolte = 0.0,
                            EkimTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TarlaId = 1,
                            UrunKategorisiId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ayçiçeği (Tunka)",
                            BeklenenRekolte = 0.0,
                            EkimTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TarlaId = 2,
                            UrunKategorisiId = 2
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.UrunKategorisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UrunKategorileri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Tahıllar"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Yağlı Tohumlar"
                        });
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Vardiya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Vardiyalar");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.YetkiAlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ModulAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YetkiTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("YetkiAlanlari");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1e1a1a1-1a1a-1a1a-1a1a-1a1a1a1a1a1a",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b2b2b2b2-2b2b-2b2b-2b2b-2b2b2b2b2b2b",
                            Name = "Kullanici",
                            NormalizedName = "KULLANICI"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.BakimKaydi", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.BakimPlani", "BakimPlani")
                        .WithMany("BakimKayitlari")
                        .HasForeignKey("BakimPlaniId");

                    b.HasOne("AgriManage.DataAccess.Models.Personel", "Personel")
                        .WithMany("BakimKayitlari")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BakimPlani");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.BakimPlani", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.BakimTipi", "BakimTipi")
                        .WithMany("BakimPlanlari")
                        .HasForeignKey("BakimTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.Ekipman", "Ekipman")
                        .WithMany("BakimPlanlari")
                        .HasForeignKey("EkipmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BakimTipi");

                    b.Navigation("Ekipman");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Depo", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.Lokasyon", "Lokasyon")
                        .WithMany("Depolar")
                        .HasForeignKey("LokasyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lokasyon");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.EkimPlani", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.Sezon", "Sezon")
                        .WithMany("EkimPlanlari")
                        .HasForeignKey("SezonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.Tarla", "Tarla")
                        .WithMany("EkimPlanlari")
                        .HasForeignKey("TarlaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sezon");

                    b.Navigation("Tarla");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Ekipman", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.EkipmanDurumu", "EkipmanDurumu")
                        .WithMany("Ekipmanlar")
                        .HasForeignKey("EkipmanDurumuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.EkipmanKategorisi", "EkipmanKategorisi")
                        .WithMany("Ekipmanlar")
                        .HasForeignKey("EkipmanKategorisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EkipmanDurumu");

                    b.Navigation("EkipmanKategorisi");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.EkipmanLog", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.Ekipman", "Ekipman")
                        .WithMany("EkipmanLoglari")
                        .HasForeignKey("EkipmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekipman");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Gorev", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.GorevDurumu", "GorevDurumu")
                        .WithMany("Gorevler")
                        .HasForeignKey("GorevDurumuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.GorevTipi", "GorevTipi")
                        .WithMany("Gorevler")
                        .HasForeignKey("GorevTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.Personel", "Personel")
                        .WithMany("AtananGorevler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.Tarla", "Tarla")
                        .WithMany("Gorevler")
                        .HasForeignKey("TarlaId");

                    b.Navigation("GorevDurumu");

                    b.Navigation("GorevTipi");

                    b.Navigation("Personel");

                    b.Navigation("Tarla");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.GorevLog", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.Gorev", "Gorev")
                        .WithMany("GorevLoglari")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Lokasyon", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.Bolge", "Bolge")
                        .WithMany("Lokasyonlar")
                        .HasForeignKey("BolgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolge");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.OperasyonelRapor", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.Gorev", "Gorev")
                        .WithMany("Raporlar")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Personel", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Personel")
                        .HasForeignKey("AgriManage.DataAccess.Models.Personel", "ApplicationUserId");

                    b.HasOne("AgriManage.DataAccess.Models.Pozisyon", "Pozisyon")
                        .WithMany("Personeller")
                        .HasForeignKey("PozisyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Pozisyon");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.PersonelVardiya", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.Personel", "Personel")
                        .WithMany("PersonelVardiyalari")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.Vardiya", "Vardiya")
                        .WithMany("PersonelVardiyalari")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Pozisyon", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.Departman", "Departman")
                        .WithMany("Pozisyonlar")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.PozisyonYetki", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.Pozisyon", "Pozisyon")
                        .WithMany("PozisyonYetkileri")
                        .HasForeignKey("PozisyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.YetkiAlani", "YetkiAlani")
                        .WithMany("PozisyonYetkileri")
                        .HasForeignKey("YetkiAlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pozisyon");

                    b.Navigation("YetkiAlani");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Sera", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.Lokasyon", "Lokasyon")
                        .WithMany("Seralar")
                        .HasForeignKey("LokasyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lokasyon");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.StokHareket", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.Depo", "Depo")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.OperasyonelRapor", "OperasyonelRapor")
                        .WithMany("KullanilanMalzemeler")
                        .HasForeignKey("OperasyonelRaporId");

                    b.HasOne("AgriManage.DataAccess.Models.StokItem", "StokItem")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("StokItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.Tedarikci", "Tedarikci")
                        .WithMany("StokHareketleri")
                        .HasForeignKey("TedarikciId");

                    b.Navigation("Depo");

                    b.Navigation("OperasyonelRapor");

                    b.Navigation("StokItem");

                    b.Navigation("Tedarikci");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.StokItem", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.Depo", "Depo")
                        .WithMany("StokItemleri")
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.StokKategorisi", "StokKategorisi")
                        .WithMany("StokItemleri")
                        .HasForeignKey("StokKategorisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depo");

                    b.Navigation("StokKategorisi");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Tarla", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.Lokasyon", "Lokasyon")
                        .WithMany("Tarlalar")
                        .HasForeignKey("LokasyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lokasyon");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.TarlaAraziTipi", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.AraziTipi", "AraziTipi")
                        .WithMany("TarlaAraziTipleri")
                        .HasForeignKey("AraziTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.Tarla", "Tarla")
                        .WithMany("TarlaAraziTipleri")
                        .HasForeignKey("TarlaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AraziTipi");

                    b.Navigation("Tarla");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Urun", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.Tarla", "Tarla")
                        .WithMany("Urunler")
                        .HasForeignKey("TarlaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.UrunKategorisi", "UrunKategorisi")
                        .WithMany("Urunler")
                        .HasForeignKey("UrunKategorisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarla");

                    b.Navigation("UrunKategorisi");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriManage.DataAccess.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AgriManage.DataAccess.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.ApplicationUser", b =>
                {
                    b.Navigation("Personel")
                        .IsRequired();
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.AraziTipi", b =>
                {
                    b.Navigation("TarlaAraziTipleri");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.BakimPlani", b =>
                {
                    b.Navigation("BakimKayitlari");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.BakimTipi", b =>
                {
                    b.Navigation("BakimPlanlari");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Bolge", b =>
                {
                    b.Navigation("Lokasyonlar");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Departman", b =>
                {
                    b.Navigation("Pozisyonlar");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Depo", b =>
                {
                    b.Navigation("StokHareketleri");

                    b.Navigation("StokItemleri");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Ekipman", b =>
                {
                    b.Navigation("BakimPlanlari");

                    b.Navigation("EkipmanLoglari");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.EkipmanDurumu", b =>
                {
                    b.Navigation("Ekipmanlar");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.EkipmanKategorisi", b =>
                {
                    b.Navigation("Ekipmanlar");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Gorev", b =>
                {
                    b.Navigation("GorevLoglari");

                    b.Navigation("Raporlar");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.GorevDurumu", b =>
                {
                    b.Navigation("Gorevler");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.GorevTipi", b =>
                {
                    b.Navigation("Gorevler");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Lokasyon", b =>
                {
                    b.Navigation("Depolar");

                    b.Navigation("Seralar");

                    b.Navigation("Tarlalar");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.OperasyonelRapor", b =>
                {
                    b.Navigation("KullanilanMalzemeler");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Personel", b =>
                {
                    b.Navigation("AtananGorevler");

                    b.Navigation("BakimKayitlari");

                    b.Navigation("PersonelVardiyalari");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Pozisyon", b =>
                {
                    b.Navigation("Personeller");

                    b.Navigation("PozisyonYetkileri");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Sezon", b =>
                {
                    b.Navigation("EkimPlanlari");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.StokItem", b =>
                {
                    b.Navigation("StokHareketleri");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.StokKategorisi", b =>
                {
                    b.Navigation("StokItemleri");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Tarla", b =>
                {
                    b.Navigation("EkimPlanlari");

                    b.Navigation("Gorevler");

                    b.Navigation("TarlaAraziTipleri");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Tedarikci", b =>
                {
                    b.Navigation("StokHareketleri");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.UrunKategorisi", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.Vardiya", b =>
                {
                    b.Navigation("PersonelVardiyalari");
                });

            modelBuilder.Entity("AgriManage.DataAccess.Models.YetkiAlani", b =>
                {
                    b.Navigation("PozisyonYetkileri");
                });
#pragma warning restore 612, 618
        }
    }
}
